<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alya Anissa Putri">
<meta name="dcterms.date" content="2024-01-21">

<title>Pengaruh Jumlah UMKM teradap PDRB di Indonesia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Jumlah UMKM teradap PDRB di Indonesia</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alya Anissa Putri </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 21, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Salah satu sektor yang sangat berperan penting dalam membantu memajukan perekonomian Indonesia adalah UMKM (Usaha Mikro, Kecil, dan Menengah). Jumlah UMKM di Indonesia sendiri pada tahun 2019 mencapai 64,2 juta unit dengan kontribusi terhadap PDB sebesar 61,07% atau Rp8.573,89 triliun. Di smping itu, UMKM telah menyerap sebesar 97% tenaga kerja Indonesia atau setara dengan 116 juta orang.</p>
<p>Ada faktor-faktor yang mempengaruhi perkembangan UMKM di Indonesia. Faktor-faktor tersebut sendiri dapat dilihat melalui sisi internal dan eksternal. Investasi menjadi salah satu faktor eksternal yang mendukung perkembangan UMKM. Investasi merupakan salah satu indicator yang menunjukkan tingkat kepercayaan investor terhadap kondisi perekonomian suatu negara. Selain itu, investasi juga dapat meningkatkan kapasitas produksi, teknologi, dan juga kualitas produk UMKM. Oleh karena itu, dengan adanya investasi UMKM yang ada dapat meningkatkan daya saing dan kinerjanya.</p>
<p>Salah satu yang menjadi indikator penilaian kinerja UMKM adalah Produk Domestik Regional Bruto (PDRB). PDRB adalah nilai tambah yang dihasilkan oleh keseluruhan unit usaha yang berada di suatu wilayah dalam kurun waktu tertentu. Kondisi ekonomi suatu wilayah dapat dilihat dari PDRB yang kemudian dapat digunakan untuk dasar perencanaan pembangunan daerah.</p>
<p>Berdasarkan latar belakang yang sudah dipaparkan terlihat jelas bahwa sangat penting untuk mengetahu pengaruh jumlah UMKM dan investasi UMKM terhadap PDRB di Indonesia. Maka dari itu, penelitian ini bertujuan untuk menganalisis pengaruh jumlah UMKM terhadap PDRB di Indonesia. Peneliti berharap dapat memberi manfaat bagi pemerintah, pelaku usaha, akademisi, dan masyarakat dalam mengembangkan potensi UMKM di Indonesia.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini bertujuan untuk menganalisis pengaruh jumlah usaha mikro, kecil, dan menengah (UMKM) terhadap produk domestik regional bruto (PDRB) provinsi di Indonesia. Dalam penelitian ini, penulis ingin mengetahui seberapa besar kontribusi UMKM terhadap PDRB di Indonesia. Data yang digunakan adalah data UMKM dan PDRB tahun 2022 yang bersumber dari Badan Pusat Statistik (BPS). Data tersebut mencakup 35 provinsi di Indonesia yang menjadi wilayah cakupan penelitian.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="a">
<li><p>Apakah UMKM mempengaruhi PDRB provinsi di Indonesia ?</p></li>
<li><p>Bagaimana hubungan UMKM terhadap PDRB provinsi di Indonesia ?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk menganalisis pengaruh jumlah usaha mikro, kecil, dan menengah (UMKM) terhadap produk domestik regional bruto (PDRB) di 35 provinsi di Indonesia, menggunakan data dari Badan Pusat Statistik (BPS) periode 2022. Manfaat dari penelitian ini adalah untuk memberikan informasi dan rekomendasi kepada pemerintah, pelaku UMKM, dan masyarakat tentang kontribusi dan potensi UMKM dalam meningkatkan pertumbuhan ekonomi.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>UMKM</strong></p>
<p>UMKM merupakan kependekan dari Usaha Mikro, Kecil, dan Menengah. UMKM adalah aktivitas ekonomi yang produktif yang dikelola oleh individu atau entitas usaha yang berskala kecil. UMKM berperan penting dalam ekonomi Indonesia, karena dapat membuka peluang kerja, menaikkan pendapatan, dan menurunkan kemiskinan. UMKM memiliki ragam jenis, seperti bidang kuliner, kecantikan, fashion, agribisnis, otomotif, dan sebagainya. Contoh UMKM di Indonesia adalah warung makan, salon, butik, peternakan, bengkel, dan lain-lain. UMKM dapat memajukan usahanya dengan cara meningkatkan kualitas pelayanan, memanfaatkan media sosial, melakukan survei pasar, mengikuti acara bazar, menjual produk secara online, menggunakan pembayaran elektronik, membangun relasi, dan mengikuti perkembangan tren.</p>
<p><strong>PDRB</strong></p>
<p>PDRB merupakan kependekan dari Produk Domestik Regional Bruto, yaitu besaran nilai tambah bruto yang berasal dari semua sektor ekonomi di wilayah suatu daerah. PDRB menunjukkan kinerja ekonomi suatu daerah dalam jangka waktu tertentu, baik berdasarkan harga berlaku maupun berdasarkan harga konstan. PDRB memiliki beberapa manfaat, di antaranya adalah untuk mengukur kemajuan ekonomi pada suatu daerah, mengetahui struktur ekonomi suatu daerah, dan digunakan sebagai dasar penyusunan kebijakan pemerintah daerah. PDRB juga dapat digunakan untuk mengetahui distribusi pendapatan antar daerah, dengan menghitung PDRB per kapita, yaitu perbandingan antara PDRB dan jumlah penduduk suatu daerah. PDRB per kapita dapat menunjukkan tingkat kesejahteraan masyarakat suatu daerah.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<colgroup>
<col style="width: 2%">
<col style="width: 39%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Provinsi</th>
<th>Jumlah.UMKM</th>
<th>PDRB</th>
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Aceh</td>
<td>1.102.000</td>
<td>276307</td>
<td>6,042181595</td>
<td>5,441391888</td>
</tr>
<tr class="even">
<td>2</td>
<td>Sumatera Utara</td>
<td>2.300.000</td>
<td>1.024.891</td>
<td>6,361727836</td>
<td>6,010677679</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Sumatera Barat</td>
<td>1.100.000</td>
<td>316.030</td>
<td>6,041392685</td>
<td>5,499728311</td>
</tr>
<tr class="even">
<td>4</td>
<td>Riau</td>
<td>1.000.000</td>
<td>1.006.063</td>
<td>6</td>
<td>6,002625177</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Jambi</td>
<td>600.000</td>
<td>230.474</td>
<td>5,77815125</td>
<td>5,362621939</td>
</tr>
<tr class="even">
<td>6</td>
<td>Sumatera Selatan</td>
<td>1.500.000</td>
<td>602.696</td>
<td>6,176091259</td>
<td>5,780098309</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Bengkulu</td>
<td>400.000</td>
<td>106.564</td>
<td>5,602059991</td>
<td>5,027610514</td>
</tr>
<tr class="even">
<td>8</td>
<td>Lampung</td>
<td>1.600.000</td>
<td>358.875</td>
<td>6,204119983</td>
<td>5,554943206</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Kepulauan Bangka Belitung</td>
<td>200.000</td>
<td>112.844</td>
<td>5,301029996</td>
<td>5,052478472</td>
</tr>
<tr class="even">
<td>10</td>
<td>Kepulauan Riau</td>
<td>400.000</td>
<td>336.227</td>
<td>5,602059991</td>
<td>5,526632586</td>
</tr>
<tr class="odd">
<td>11</td>
<td>DKI Jakarta</td>
<td>2.800.000</td>
<td>2.857.079</td>
<td>6,447158031</td>
<td>6,455922249</td>
</tr>
<tr class="even">
<td>12</td>
<td>Jawa Barat</td>
<td>2.600.000</td>
<td>2.518.512</td>
<td>6,414973348</td>
<td>6,401144024</td>
</tr>
<tr class="odd">
<td>13</td>
<td>Jawa Tengah</td>
<td>4.500.000</td>
<td>1.692.055</td>
<td>6,653212514</td>
<td>6,228414476</td>
</tr>
<tr class="even">
<td>14</td>
<td>DI Yogyakarta</td>
<td>800.000</td>
<td>246.676</td>
<td>5,903089987</td>
<td>5,392126897</td>
</tr>
<tr class="odd">
<td>15</td>
<td>Jawa Timur</td>
<td>4.000.000</td>
<td>2.412.433</td>
<td>6,602059991</td>
<td>6,382455261</td>
</tr>
<tr class="even">
<td>16</td>
<td>Banten</td>
<td>1.500.000</td>
<td>1.057.895</td>
<td>6,176091259</td>
<td>6,024442565</td>
</tr>
<tr class="odd">
<td>17</td>
<td>Bali</td>
<td>800.000</td>
<td>252.533</td>
<td>5,903089987</td>
<td>5,402318138</td>
</tr>
<tr class="even">
<td>18</td>
<td>Nusa Tenggara Barat</td>
<td>900.000</td>
<td>184.798</td>
<td>5,954242509</td>
<td>5,266697267</td>
</tr>
<tr class="odd">
<td>19</td>
<td>Nusa Tenggara Timur</td>
<td>1.000.000</td>
<td>175.249</td>
<td>6</td>
<td>5,243655548</td>
</tr>
<tr class="even">
<td>20</td>
<td>Kalimantan Barat</td>
<td>800.000</td>
<td>239.732</td>
<td>5,903089987</td>
<td>5,379726009</td>
</tr>
<tr class="odd">
<td>21</td>
<td>Kalimantan Tengah</td>
<td>400.000</td>
<td>221.721</td>
<td>5,602059991</td>
<td>5,345806829</td>
</tr>
<tr class="even">
<td>22</td>
<td>Kalimantan Selatan</td>
<td>900.000</td>
<td>314.719</td>
<td>5,954242509</td>
<td>5,497922963</td>
</tr>
<tr class="odd">
<td>23</td>
<td>Kalimantan Timur</td>
<td>600.000</td>
<td>1.015.776</td>
<td>5,77815125</td>
<td>6,006797947</td>
</tr>
<tr class="even">
<td>24</td>
<td>Kalimantan Utara</td>
<td>200.000</td>
<td>120.082</td>
<td>5,301029996</td>
<td>5,079477913</td>
</tr>
<tr class="odd">
<td>25</td>
<td>Sulawesi Utara</td>
<td>500.000</td>
<td>183.789</td>
<td>5,698970004</td>
<td>5,264319515</td>
</tr>
<tr class="even">
<td>26</td>
<td>Sulawesi Tengah</td>
<td>500.000</td>
<td>154.648</td>
<td>5,698970004</td>
<td>5,189344308</td>
</tr>
<tr class="odd">
<td>27</td>
<td>Sulawesi Selatan</td>
<td>1.800.000</td>
<td>664.596</td>
<td>6,255272505</td>
<td>5,822557723</td>
</tr>
<tr class="even">
<td>28</td>
<td>Sulawesi Tenggara</td>
<td>500.000</td>
<td>156.757</td>
<td>5,698970004</td>
<td>5,195226943</td>
</tr>
<tr class="odd">
<td>29</td>
<td>Gorontalo</td>
<td>300.000</td>
<td>72.570</td>
<td>5,477121255</td>
<td>4,860757123</td>
</tr>
<tr class="even">
<td>30</td>
<td>Sulawesi Barat</td>
<td>300.000</td>
<td>83.581</td>
<td>5,477121255</td>
<td>4,922107563</td>
</tr>
<tr class="odd">
<td>31</td>
<td>Maluku</td>
<td>300.000</td>
<td>97.585</td>
<td>5,477121255</td>
<td>4,989383066</td>
</tr>
<tr class="even">
<td>32</td>
<td>Maluku Utara</td>
<td>200.000</td>
<td>74.411</td>
<td>5,301029996</td>
<td>4,871637141</td>
</tr>
<tr class="odd">
<td>33</td>
<td>Papua Barat</td>
<td>200.000</td>
<td>108.267</td>
<td>5,301029996</td>
<td>5,034496103</td>
</tr>
<tr class="even">
<td>34</td>
<td>Papua</td>
<td>300.000</td>
<td>326.703</td>
<td>5,477121255</td>
<td>5,514153122</td>
</tr>
</tbody>
</table>
<p>Data diambil dari Badan Pusat Statistik (BPS) Indonesia tahun 2022 yang kemudian diolah dengan melakukan log pada kedua variabel, sehingga menghasilkan data variabel x dari jumlah UMKM dan variabel y dari data PDRB (miliar rupiah).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>umkm<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/tugasuas/alya/umkm.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(umkm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Provinsi         `Jumlah UMKM` `PDRB (miliar rupiah)`     x     y
  &lt;chr&gt;            &lt;chr&gt;         &lt;chr&gt;                  &lt;dbl&gt; &lt;dbl&gt;
1 Aceh             1102000       276307                  6.04  5.44
2 Sumatera Utara   2.300.000     1024891                 6.36  6.01
3 Sumatera Barat   1.100.000     316.030                 6.04  5.50
4 Riau             1.000.000     1.006.063               6     6.00
5 Jambi            600.000       230.474                 5.78  5.36
6 Sumatera Selatan 1.500.000     602.696                 6.18  5.78</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>umkm,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"#CD7054"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan UMKM dan PDRB di Indonesia"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"UMKM"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"PDRB"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik"</span>)<span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Penelitian ini menggunakan metode regresi univariat, dengan menggunakan data UMKM dan PDRB provinsi di Indonesia tahun 2022. . Analisis ini bertujuan untuk menguji pengaruh variabel independen (jumlah UMKM) terhadap variabel dependen (PDRB). Dengan spesifikasi sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah PDRB dan <span class="math inline">\(x_t\)</span> adalah UMKM.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients</th>
<th>Estimate</th>
<th>t value</th>
<th>Pr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-0.5409</td>
<td>-0.843</td>
<td>0.405</td>
</tr>
<tr class="even">
<td>x</td>
<td>1.0293</td>
<td>9.439</td>
<td>9.13e-11</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
y_{t}=\ -0.5409 + \ 1.0293x+\mu_t
\]</span></p>
<p>Nilai koefisien regresi sebesar 1.0293, yang berarti jika x bertambah 1 satuan, maka y akan bertambah 1.0293 satuan, dengan asumsi variabel lain tetap. Nilai t hitung untuk koefisien regresi adalah 9.439, yang lebih besar dari nilai t tabel pada tingkat signifikansi 5%. Hal ini berarti koefisien regresi signifikan secara statistik. Sedangkan nilai p-value untuk koefisien regresi adalah 9.13e-11, yang lebih kecil dari tingkat signifikansi 5%, yaitu 0.05. Hal ini berarti koefisien regresi signifikan secara statistik.</p>
<p>Sedangkan untuk nilai konstanta (intercept) adalah -0.5409, yang berarti jika x bernilai 0, maka y bernilai -0.5409. Untuk nilai t hitung untuk konstanta adalah -0.843, yang lebih kecil dari nilai t tabel pada tingkat signifikansi 5%. Hal ini berarti konstanta tidak signifikan secara statistik.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>umkm<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"umkm.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>umkm)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = umkm)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.39152 -0.15259 -0.06818  0.13448  0.59999 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.5409     0.6414  -0.843    0.405    
x             1.0293     0.1091   9.439 9.13e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2392 on 32 degrees of freedom
Multiple R-squared:  0.7357,    Adjusted R-squared:  0.7275 
F-statistic:  89.1 on 1 and 32 DF,  p-value: 9.129e-11</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>umkm<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(umkm<span class="sc">$</span>y,umkm<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"PDRB"</span>,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'#5CACEE'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>umkm<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(umkm<span class="sc">$</span>x,umkm<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"UMKM"</span>,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'#CDB5CD'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Nilai R-squared adalah 0.7357, yang berarti variabel x dapat menjelaskan 73.57% variasi dari variabel y. Nilai ini menunjukkan bahwa tingkat keterkaitan antara x dan y kuat.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Dapat disimpulkan bahwa UMKM memiliki pengaruh positif terhadap PDRB di Indonesia, dapat dilihat dari nilai koefisien yang positif dan signifikan. Faktor yang mungkin terjadi terhadap hubungan UMKM dan PDRB adalah: UMKM mampu meningkatkan nilai produksi, pendapatan, dan lapangan kerja. UMKM juga menjadi salah satu faktor yang menentukan kesejahteraan masyarakat dan pembangunan manusia. Selain itu,UMKM memiliki peran penting sebagai <em>critical engine</em> perekonomian national, terutama dalam menghadapi dampak pandemi covid-19.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Suci, Y. R. (2017). Perkembangan UMKM (Usaha mikro kecil dan menengah) di Indonesia. jurnal ilmiah cano ekonomos, 6(1), 51-58.</p>
<p>Tasyim, D. A., Kawung, G. M., &amp; Siwu, H. F. D. (2021). Pengaruh Jumlah Unit Usaha UMKM Dan PDRB Terhadap Penyerapan Tenaga Kerja Di Sulawesi Utara. Jurnal EMBA: Jurnal Riset Ekonomi, Manajemen, Bisnis dan Akuntansi, 9(3).</p>
<p>Shofia, A., Triha, H., Putri, R. M., Alius, M., &amp; Satria, T. F. (2023). Pengaruh Jumlah Angkatan Kerja, Jumlah UMKM, dan Inflasi Terhadap Laju PDRB Kota Padang. Jurnal Surya Teknika, 10(2), 858-865.</p>
<p>Aulia, R. (2021). Pengaruh pertumbuhan umkm terhadap pertumbuhan ekonomi di Ponorogo periode 2013-2017 (Doctoral dissertation, IAIN Ponorogo).</p>
<p>Putra, A. C. (2022). Pengaruh Pertumbuhan PDRB Usaha Mikro Kecil Menengah (UMKM) Terhadap Pertumbuhan Ekonomi Surabaya. Jurnal Lemhannas RI, 10(2), 65-78.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>